version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: gendev
    environment:
      POSTGRES_DB: gendev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network

volumes:
  postgres-data:
networks:
  dev-network: