networks:
  my-network:
    driver: bridge
services:
  pg-0:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=${POSTGRES_CUSTOM_PASSWORD}
      - POSTGRESQL_DATABASE=gendev
      - REPMGR_PASSWORD=${POSTGRES_REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
  pg-1:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=${POSTGRES_CUSTOM_PASSWORD}
      - POSTGRESQL_DATABASE=gendev
      - REPMGR_PASSWORD=${POSTGRES_REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
  pgpool:
    image: bitnami/pgpool:4
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=${POSTGRES_CUSTOM_PASSWORD}
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=${POSTGRES_PASSWORD}
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_QUERY_CACHE=yes
      - PGPOOL_ENABLE_TABLE_CACHE=yes
      - PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
  next-0:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
       - 3000
    environment:
        - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@pgpool:5432/gendev?schema=public&pgbouncer=true
        - JWT_SECRET=${JWT_SECRET}
    depends_on:
        - pgpool
        - pg-0
        - pg-1
  next-1:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@pgpool:5432/gendev?schema=public&pgbouncer=true
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - pgpool
      - pg-0
      - pg-1
  nginx:
    build:
        context: nginx
        dockerfile: Dockerfile
    container_name: nginx_load_balancer
    ports:
      - "80:80"
    depends_on:
      - next-0
      - next-1
volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local